import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const lahoreAreas = [
  { area: "Gulberg III", street: "Main Boulevard", city: "Lahore" },
  { area: "DHA Phase 5", street: "Badar Commercial", city: "Lahore" },
  { area: "Model Town", street: "Main Boulevard Model Town", city: "Lahore" },
  { area: "Johar Town", street: "Khayaban-e-Jinnah", city: "Lahore" },
  { area: "Bahria Town", street: "Sector C Main Road", city: "Lahore" },
  { area: "Garden Town", street: "Abuzar Block", city: "Lahore" },
  { area: "Cantt", street: "Sarwar Road", city: "Lahore" },
  { area: "Shadman", street: "Shadman Market Road", city: "Lahore" },
  { area: "Faisal Town", street: "Block C Main Road", city: "Lahore" },
  { area: "Wapda Town", street: "Phase 1 Main Boulevard", city: "Lahore" },
];

const doctors = [
  // ── CARDIOLOGIST ──
  {
    full_name: "Ahmad Raza Khan",
    email: "dr.ahmad.raza@apnadoctor.pk",
    phone: "0300-1234001",
    gender: "male",
    specialization: "Cardiologist",
    qualification: "MBBS, FCPS (Cardiology), Fellowship AHA",
    experience: 18,
    bio: "Dr. Ahmad Raza Khan is a senior cardiologist with 18 years of experience in interventional cardiology. He specializes in coronary artery disease, heart failure management, and cardiac catheterization. He has performed over 2,000 angioplasties and is a fellow of the American Heart Association.",
    clinic_name: "Lahore Heart Clinic",
    clinic_address: "12-A Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-CAR-10021",
    consultation_fee: 3000,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.8,
    total_reviews: 312,
    total_appointments: 890,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Sana Mirza",
    email: "dr.sana.mirza@apnadoctor.pk",
    phone: "0300-1234002",
    gender: "female",
    specialization: "Cardiologist",
    qualification: "MBBS, FCPS (Cardiology), MRCP (UK)",
    experience: 12,
    bio: "Dr. Sana Mirza is a consultant cardiologist specializing in echocardiography, hypertension management, and preventive cardiology. She completed her fellowship at Aga Khan University and is known for her patient-centered approach to heart disease management.",
    clinic_name: "Cardiac Care Centre DHA",
    clinic_address: "45 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-CAR-10022",
    consultation_fee: 2500,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 245,
    total_appointments: 670,
    marital_status: "married",
    ...lahoreAreas[1],
  },
  {
    full_name: "Muhammad Tariq Mahmood",
    email: "dr.tariq.mahmood@apnadoctor.pk",
    phone: "0300-1234003",
    gender: "male",
    specialization: "Cardiologist",
    qualification: "MBBS, MD (Cardiology), FACC",
    experience: 22,
    bio: "Professor Tariq Mahmood is one of Lahore's most experienced cardiologists with over 22 years in clinical practice. He is a Fellow of the American College of Cardiology and has expertise in complex coronary interventions, structural heart disease, and cardiac rehabilitation.",
    clinic_name: "Model Town Cardiac Centre",
    clinic_address: "7 Main Boulevard, Model Town, Lahore",
    pmdc_number: "PMDC-CAR-10023",
    consultation_fee: 4000,
    languages: ["Urdu", "English"],
    average_rating: 4.9,
    total_reviews: 520,
    total_appointments: 1450,
    marital_status: "married",
    ...lahoreAreas[2],
  },
  {
    full_name: "Nadia Hussain",
    email: "dr.nadia.hussain@apnadoctor.pk",
    phone: "0300-1234004",
    gender: "female",
    specialization: "Cardiologist",
    qualification: "MBBS, FCPS (Cardiology)",
    experience: 9,
    bio: "Dr. Nadia Hussain is a consultant cardiologist with special interest in women's heart health and cardiac imaging. She trained at Punjab Institute of Cardiology and has expertise in stress echocardiography and Holter monitoring.",
    clinic_name: "Johar Town Heart Clinic",
    clinic_address: "22 Khayaban-e-Jinnah, Johar Town, Lahore",
    pmdc_number: "PMDC-CAR-10024",
    consultation_fee: 2000,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.6,
    total_reviews: 189,
    total_appointments: 510,
    marital_status: "single",
    ...lahoreAreas[3],
  },
  {
    full_name: "Imran Sheikh",
    email: "dr.imran.sheikh@apnadoctor.pk",
    phone: "0300-1234005",
    gender: "male",
    specialization: "Cardiologist",
    qualification: "MBBS, FCPS (Cardiology), FSCAI",
    experience: 15,
    bio: "Dr. Imran Sheikh is an interventional cardiologist and Fellow of the Society for Cardiovascular Angiography and Interventions. He specializes in complex angioplasty, peripheral vascular interventions, and carotid artery stenting. He has trained at leading cardiac centers in the UK and USA.",
    clinic_name: "Bahria Cardiac Institute",
    clinic_address: "Sector C Main Road, Bahria Town, Lahore",
    pmdc_number: "PMDC-CAR-10025",
    consultation_fee: 3500,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 278,
    total_appointments: 780,
    marital_status: "married",
    ...lahoreAreas[4],
  },

  // ── DENTIST ──
  {
    full_name: "Ayesha Qureshi",
    email: "dr.ayesha.qureshi@apnadoctor.pk",
    phone: "0300-1234011",
    gender: "female",
    specialization: "Dentist",
    qualification: "BDS, FCPS (Orthodontics)",
    experience: 10,
    bio: "Dr. Ayesha Qureshi is a specialist orthodontist offering braces, Invisalign, and comprehensive orthodontic treatment for children and adults. She completed her FCPS from KEMU and has a special interest in early orthodontic intervention and cleft palate management.",
    clinic_name: "Bright Smiles Dental Clinic",
    clinic_address: "15 Abuzar Block, Garden Town, Lahore",
    pmdc_number: "PMDC-DEN-20011",
    consultation_fee: 1500,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.7,
    total_reviews: 203,
    total_appointments: 620,
    marital_status: "married",
    ...lahoreAreas[5],
  },
  {
    full_name: "Hassan Ali Baig",
    email: "dr.hassan.baig@apnadoctor.pk",
    phone: "0300-1234012",
    gender: "male",
    specialization: "Dentist",
    qualification: "BDS, MCPS (Restorative Dentistry)",
    experience: 8,
    bio: "Dr. Hassan Ali Baig specializes in cosmetic and restorative dentistry including veneers, crowns, implants, and teeth whitening. He uses digital smile design technology to help patients achieve their ideal smile. He trained at de'Montmorency College of Dentistry.",
    clinic_name: "DHA Dental Studio",
    clinic_address: "78 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-DEN-20012",
    consultation_fee: 1800,
    languages: ["Urdu", "English"],
    average_rating: 4.6,
    total_reviews: 167,
    total_appointments: 490,
    marital_status: "single",
    ...lahoreAreas[1],
  },
  {
    full_name: "Farah Naz Siddiqui",
    email: "dr.farah.siddiqui@apnadoctor.pk",
    phone: "0300-1234013",
    gender: "female",
    specialization: "Dentist",
    qualification: "BDS, FCPS (Oral Surgery)",
    experience: 14,
    bio: "Dr. Farah Naz Siddiqui is an oral and maxillofacial surgeon with expertise in dental implants, wisdom tooth extraction, bone grafting, and treatment of oral cancer. She has performed over 3,000 implant procedures and is a trainer for a major implant system.",
    clinic_name: "Gulberg Oral Surgery Centre",
    clinic_address: "34-B Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-DEN-20013",
    consultation_fee: 2000,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 289,
    total_appointments: 760,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Usman Farooq",
    email: "dr.usman.farooq@apnadoctor.pk",
    phone: "0300-1234014",
    gender: "male",
    specialization: "Dentist",
    qualification: "BDS, MCPS (Pediatric Dentistry)",
    experience: 7,
    bio: "Dr. Usman Farooq is a pediatric dentist with special training in treating children with dental anxiety. He uses behavior management techniques and nitrous oxide sedation to make dental visits comfortable for children. He runs a child-friendly dental clinic in Johar Town.",
    clinic_name: "Kids Dental World",
    clinic_address: "11 Khayaban-e-Jinnah, Johar Town, Lahore",
    pmdc_number: "PMDC-DEN-20014",
    consultation_fee: 1200,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.9,
    total_reviews: 412,
    total_appointments: 1100,
    marital_status: "married",
    ...lahoreAreas[3],
  },
  {
    full_name: "Zainab Malik",
    email: "dr.zainab.malik@apnadoctor.pk",
    phone: "0300-1234015",
    gender: "female",
    specialization: "Dentist",
    qualification: "BDS, Diploma Endodontics (UK)",
    experience: 11,
    bio: "Dr. Zainab Malik is an endodontics specialist focusing on root canal treatment using rotary and reciprocating systems. She trained in the UK and brings modern endodontic techniques to Lahore. She has a reputation for painless root canal procedures.",
    clinic_name: "Cantt Dental Care",
    clinic_address: "22 Sarwar Road, Cantt, Lahore",
    pmdc_number: "PMDC-DEN-20015",
    consultation_fee: 2200,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 198,
    total_appointments: 540,
    marital_status: "single",
    ...lahoreAreas[6],
  },

  // ── DERMATOLOGIST ──
  {
    full_name: "Rabia Anwar",
    email: "dr.rabia.anwar@apnadoctor.pk",
    phone: "0300-1234021",
    gender: "female",
    specialization: "Dermatologist",
    qualification: "MBBS, FCPS (Dermatology)",
    experience: 11,
    bio: "Dr. Rabia Anwar is a consultant dermatologist specializing in medical and cosmetic dermatology. She offers treatments for acne, eczema, psoriasis, hair loss, and performs laser treatments and chemical peels. She completed her FCPS from Allama Iqbal Medical College.",
    clinic_name: "Glow Skin Clinic",
    clinic_address: "8 Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-DERM-30021",
    consultation_fee: 2000,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 356,
    total_appointments: 980,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Bilal Chaudhry",
    email: "dr.bilal.chaudhry@apnadoctor.pk",
    phone: "0300-1234022",
    gender: "male",
    specialization: "Dermatologist",
    qualification: "MBBS, MCPS (Dermatology), Diploma Aesthetics (UK)",
    experience: 9,
    bio: "Dr. Bilal Chaudhry is a dermatologist and aesthetic physician with expertise in skin rejuvenation, Botox, fillers, and PRP therapy. He trained in aesthetic medicine in the UK and is known for natural-looking cosmetic results.",
    clinic_name: "DHA Skin & Aesthetics",
    clinic_address: "55 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-DERM-30022",
    consultation_fee: 2500,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.6,
    total_reviews: 221,
    total_appointments: 590,
    marital_status: "single",
    ...lahoreAreas[1],
  },
  {
    full_name: "Hina Rashid",
    email: "dr.hina.rashid@apnadoctor.pk",
    phone: "0300-1234023",
    gender: "female",
    specialization: "Dermatologist",
    qualification: "MBBS, FCPS (Dermatology), Fellowship Hair Transplant",
    experience: 13,
    bio: "Dr. Hina Rashid is a dermatologist with specialized training in hair restoration including FUE hair transplant, PRP for hair loss, and scalp micro-pigmentation. She has performed over 500 hair transplant procedures and runs a dedicated hair loss clinic.",
    clinic_name: "Model Town Derma Clinic",
    clinic_address: "19 Main Boulevard, Model Town, Lahore",
    pmdc_number: "PMDC-DERM-30023",
    consultation_fee: 2000,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 274,
    total_appointments: 730,
    marital_status: "married",
    ...lahoreAreas[2],
  },
  {
    full_name: "Kamran Yousuf",
    email: "dr.kamran.yousuf@apnadoctor.pk",
    phone: "0300-1234024",
    gender: "male",
    specialization: "Dermatologist",
    qualification: "MBBS, MCPS (Dermatology)",
    experience: 7,
    bio: "Dr. Kamran Yousuf is a dermatologist with focus on pediatric dermatology and inflammatory skin conditions. He manages complex cases of atopic dermatitis, vitiligo, and urticaria. He is affiliated with Services Hospital Lahore.",
    clinic_name: "Shadman Skin Centre",
    clinic_address: "6 Shadman Market Road, Shadman, Lahore",
    pmdc_number: "PMDC-DERM-30024",
    consultation_fee: 1500,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.5,
    total_reviews: 143,
    total_appointments: 410,
    marital_status: "married",
    ...lahoreAreas[7],
  },
  {
    full_name: "Mariam Tahir",
    email: "dr.mariam.tahir@apnadoctor.pk",
    phone: "0300-1234025",
    gender: "female",
    specialization: "Dermatologist",
    qualification: "MBBS, FCPS (Dermatology), MRCP (Dermatology, UK)",
    experience: 16,
    bio: "Dr. Mariam Tahir is a senior dermatologist with dual qualification from Pakistan and the UK. She specializes in autoimmune skin diseases, cutaneous lymphoma, and complex dermatological conditions. She is a visiting consultant at multiple Lahore hospitals.",
    clinic_name: "Faisal Town Dermatology Centre",
    clinic_address: "3 Block C Main Road, Faisal Town, Lahore",
    pmdc_number: "PMDC-DERM-30025",
    consultation_fee: 3000,
    languages: ["Urdu", "English"],
    average_rating: 4.9,
    total_reviews: 387,
    total_appointments: 1020,
    marital_status: "married",
    ...lahoreAreas[8],
  },

  // ── ENT SPECIALIST ──
  {
    full_name: "Salman Akhtar",
    email: "dr.salman.akhtar@apnadoctor.pk",
    phone: "0300-1234031",
    gender: "male",
    specialization: "ENT Specialist",
    qualification: "MBBS, FCPS (ENT), Fellowship Rhinology (Germany)",
    experience: 14,
    bio: "Dr. Salman Akhtar is a consultant ENT surgeon with sub-specialty training in rhinology and endoscopic sinus surgery. He has performed over 1,500 FESS procedures and specializes in management of chronic sinusitis, nasal polyps, and septoplasty.",
    clinic_name: "Gulberg ENT & Head Neck Centre",
    clinic_address: "25 Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-ENT-40031",
    consultation_fee: 2000,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.7,
    total_reviews: 267,
    total_appointments: 710,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Amna Zafar",
    email: "dr.amna.zafar@apnadoctor.pk",
    phone: "0300-1234032",
    gender: "female",
    specialization: "ENT Specialist",
    qualification: "MBBS, FCPS (ENT)",
    experience: 9,
    bio: "Dr. Amna Zafar is an ENT specialist with expertise in pediatric ENT, hearing assessment, and cochlear implant candidacy evaluation. She manages conditions including tonsillitis, adenoids, and pediatric hearing loss. She works closely with speech therapists for comprehensive care.",
    clinic_name: "DHA Hearing & ENT Clinic",
    clinic_address: "67 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-ENT-40032",
    consultation_fee: 1800,
    languages: ["Urdu", "English"],
    average_rating: 4.6,
    total_reviews: 189,
    total_appointments: 520,
    marital_status: "single",
    ...lahoreAreas[1],
  },
  {
    full_name: "Faisal Hameed",
    email: "dr.faisal.hameed@apnadoctor.pk",
    phone: "0300-1234033",
    gender: "male",
    specialization: "ENT Specialist",
    qualification: "MBBS, FCPS (ENT), Fellowship Head & Neck Surgery",
    experience: 17,
    bio: "Dr. Faisal Hameed is a head and neck surgeon with expertise in thyroid surgery, salivary gland surgery, and head and neck oncology. He trained at Shaukat Khanum Memorial Cancer Hospital and has special skills in minimally invasive thyroidectomy.",
    clinic_name: "Cantt Head Neck Surgical Centre",
    clinic_address: "14 Sarwar Road, Cantt, Lahore",
    pmdc_number: "PMDC-ENT-40033",
    consultation_fee: 2500,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 312,
    total_appointments: 840,
    marital_status: "married",
    ...lahoreAreas[6],
  },
  {
    full_name: "Sobia Khalid",
    email: "dr.sobia.khalid@apnadoctor.pk",
    phone: "0300-1234034",
    gender: "female",
    specialization: "ENT Specialist",
    qualification: "MBBS, MCPS (ENT)",
    experience: 7,
    bio: "Dr. Sobia Khalid is an ENT specialist with focus on audiology and vestibular disorders. She manages dizziness, vertigo, tinnitus, and balance problems using evidence-based vestibular rehabilitation. She is certified in BPPV repositioning maneuvers.",
    clinic_name: "Johar Town ENT Clinic",
    clinic_address: "33 Khayaban-e-Jinnah, Johar Town, Lahore",
    pmdc_number: "PMDC-ENT-40034",
    consultation_fee: 1500,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.5,
    total_reviews: 134,
    total_appointments: 380,
    marital_status: "married",
    ...lahoreAreas[3],
  },
  {
    full_name: "Omer Farhan",
    email: "dr.omer.farhan@apnadoctor.pk",
    phone: "0300-1234035",
    gender: "male",
    specialization: "ENT Specialist",
    qualification: "MBBS, FCPS (ENT), Diploma Otology (UK)",
    experience: 12,
    bio: "Dr. Omer Farhan is an otologist specializing in ear surgery, cochlear implants, and microscopic ear procedures. He trained in the UK and has expertise in stapedectomy, myringoplasty, and chronic ear disease management.",
    clinic_name: "Model Town Ear Clinic",
    clinic_address: "5 Main Boulevard, Model Town, Lahore",
    pmdc_number: "PMDC-ENT-40035",
    consultation_fee: 2200,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 223,
    total_appointments: 610,
    marital_status: "married",
    ...lahoreAreas[2],
  },

  // ── GASTROENTEROLOGIST ──
  {
    full_name: "Arif Mehmood",
    email: "dr.arif.mehmood@apnadoctor.pk",
    phone: "0300-1234041",
    gender: "male",
    specialization: "Gastroenterologist",
    qualification: "MBBS, FCPS (Gastroenterology), Fellowship Endoscopy (USA)",
    experience: 16,
    bio: "Dr. Arif Mehmood is a consultant gastroenterologist and advanced endoscopist. He specializes in therapeutic endoscopy including ERCP, EUS, and endoscopic resection of GI tumors. He has trained at Mayo Clinic and is an expert in management of IBD and liver disease.",
    clinic_name: "Gulberg GI & Liver Centre",
    clinic_address: "18 Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-GAS-50041",
    consultation_fee: 3000,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 298,
    total_appointments: 810,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Saima Pervez",
    email: "dr.saima.pervez@apnadoctor.pk",
    phone: "0300-1234042",
    gender: "female",
    specialization: "Gastroenterologist",
    qualification: "MBBS, FCPS (Gastroenterology)",
    experience: 10,
    bio: "Dr. Saima Pervez is a gastroenterologist with special interest in hepatology and management of liver cirrhosis. She has expertise in fibroscan assessment, viral hepatitis treatment, and nutrition in liver disease. She runs a dedicated liver clinic.",
    clinic_name: "DHA Liver & GI Clinic",
    clinic_address: "89 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-GAS-50042",
    consultation_fee: 2500,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.7,
    total_reviews: 234,
    total_appointments: 640,
    marital_status: "married",
    ...lahoreAreas[1],
  },
  {
    full_name: "Junaid Hassan",
    email: "dr.junaid.hassan@apnadoctor.pk",
    phone: "0300-1234043",
    gender: "male",
    specialization: "Gastroenterologist",
    qualification: "MBBS, MD (Gastroenterology)",
    experience: 13,
    bio: "Dr. Junaid Hassan is a gastroenterologist specializing in functional GI disorders, irritable bowel syndrome, and celiac disease. He uses a holistic approach combining medical therapy with dietary guidance and psychological support for chronic gut conditions.",
    clinic_name: "Bahria Digestive Health Centre",
    clinic_address: "Sector C Main Road, Bahria Town, Lahore",
    pmdc_number: "PMDC-GAS-50043",
    consultation_fee: 2000,
    languages: ["Urdu", "English"],
    average_rating: 4.6,
    total_reviews: 178,
    total_appointments: 490,
    marital_status: "single",
    ...lahoreAreas[4],
  },
  {
    full_name: "Uzma Rafiq",
    email: "dr.uzma.rafiq@apnadoctor.pk",
    phone: "0300-1234044",
    gender: "female",
    specialization: "Gastroenterologist",
    qualification: "MBBS, FCPS (Gastroenterology), MRCP (UK)",
    experience: 14,
    bio: "Dr. Uzma Rafiq is a consultant gastroenterologist with dual qualification from Pakistan and the UK. She specializes in upper and lower GI endoscopy, colorectal cancer screening, and management of inflammatory bowel disease. She is a trainer for GI endoscopy.",
    clinic_name: "Cantt Gastroenterology Clinic",
    clinic_address: "30 Sarwar Road, Cantt, Lahore",
    pmdc_number: "PMDC-GAS-50044",
    consultation_fee: 2800,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 312,
    total_appointments: 850,
    marital_status: "married",
    ...lahoreAreas[6],
  },
  {
    full_name: "Shahid Nawaz",
    email: "dr.shahid.nawaz@apnadoctor.pk",
    phone: "0300-1234045",
    gender: "male",
    specialization: "Gastroenterologist",
    qualification: "MBBS, FCPS (Gastroenterology)",
    experience: 8,
    bio: "Dr. Shahid Nawaz is a gastroenterologist with expertise in pediatric gastroenterology and eosinophilic esophagitis. He manages GERD, peptic ulcer disease, and H. pylori infection using the latest evidence-based protocols. He is affiliated with Children's Hospital Lahore.",
    clinic_name: "Johar Town GI Centre",
    clinic_address: "44 Khayaban-e-Jinnah, Johar Town, Lahore",
    pmdc_number: "PMDC-GAS-50045",
    consultation_fee: 1800,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.5,
    total_reviews: 156,
    total_appointments: 420,
    marital_status: "married",
    ...lahoreAreas[3],
  },

  // ── GENERAL PHYSICIAN ──
  {
    full_name: "Khalid Mehmood Butt",
    email: "dr.khalid.butt@apnadoctor.pk",
    phone: "0300-1234051",
    gender: "male",
    specialization: "General Physician",
    qualification: "MBBS, MCPS (Family Medicine)",
    experience: 20,
    bio: "Dr. Khalid Mehmood Butt is a highly experienced general physician with 20 years of practice. He manages a wide range of acute and chronic conditions including diabetes, hypertension, respiratory infections, and general health checkups. He is known for his thorough consultations.",
    clinic_name: "Model Town Family Clinic",
    clinic_address: "2 Main Boulevard, Model Town, Lahore",
    pmdc_number: "PMDC-GP-60051",
    consultation_fee: 1000,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.7,
    total_reviews: 567,
    total_appointments: 2100,
    marital_status: "married",
    ...lahoreAreas[2],
  },
  {
    full_name: "Rubina Saleem",
    email: "dr.rubina.saleem@apnadoctor.pk",
    phone: "0300-1234052",
    gender: "female",
    specialization: "General Physician",
    qualification: "MBBS, DCPS (Family Medicine)",
    experience: 15,
    bio: "Dr. Rubina Saleem is a family medicine physician with special interest in women's health and preventive medicine. She provides comprehensive primary care including immunizations, health screenings, and chronic disease management for all age groups.",
    clinic_name: "Shadman Family Health Centre",
    clinic_address: "9 Shadman Market Road, Shadman, Lahore",
    pmdc_number: "PMDC-GP-60052",
    consultation_fee: 800,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.8,
    total_reviews: 489,
    total_appointments: 1800,
    marital_status: "married",
    ...lahoreAreas[7],
  },
  {
    full_name: "Naveed Iqbal",
    email: "dr.naveed.iqbal@apnadoctor.pk",
    phone: "0300-1234053",
    gender: "male",
    specialization: "General Physician",
    qualification: "MBBS, FCPS (Internal Medicine)",
    experience: 12,
    bio: "Dr. Naveed Iqbal is an internal medicine physician with expertise in managing complex medical conditions, multi-system diseases, and hospitalized patients. He has strong skills in diagnostic workup and is known for his systematic approach to difficult cases.",
    clinic_name: "Wapda Town Medical Centre",
    clinic_address: "Phase 1 Main Boulevard, Wapda Town, Lahore",
    pmdc_number: "PMDC-GP-60053",
    consultation_fee: 1200,
    languages: ["Urdu", "English"],
    average_rating: 4.6,
    total_reviews: 312,
    total_appointments: 1200,
    marital_status: "married",
    ...lahoreAreas[9],
  },
  {
    full_name: "Tahira Noman",
    email: "dr.tahira.noman@apnadoctor.pk",
    phone: "0300-1234054",
    gender: "female",
    specialization: "General Physician",
    qualification: "MBBS, MCPS (Internal Medicine)",
    experience: 8,
    bio: "Dr. Tahira Noman is a general physician focusing on diabetes management and metabolic syndrome. She uses a lifestyle-first approach combined with evidence-based pharmacotherapy. She runs a dedicated diabetes education program for her patients.",
    clinic_name: "Faisal Town Medical Clinic",
    clinic_address: "7 Block C Main Road, Faisal Town, Lahore",
    pmdc_number: "PMDC-GP-60054",
    consultation_fee: 900,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.7,
    total_reviews: 278,
    total_appointments: 980,
    marital_status: "single",
    ...lahoreAreas[8],
  },
  {
    full_name: "Asim Rehman",
    email: "dr.asim.rehman@apnadoctor.pk",
    phone: "0300-1234055",
    gender: "male",
    specialization: "General Physician",
    qualification: "MBBS, MRCP (UK)",
    experience: 18,
    bio: "Dr. Asim Rehman holds the MRCP from the Royal College of Physicians UK and brings international standards of care to his patients. He specializes in hypertension, thyroid disorders, and complex multi-morbidity cases. He is a visiting consultant at Lahore General Hospital.",
    clinic_name: "Gulberg Internal Medicine Clinic",
    clinic_address: "42 Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-GP-60055",
    consultation_fee: 1500,
    languages: ["Urdu", "English"],
    average_rating: 4.9,
    total_reviews: 423,
    total_appointments: 1560,
    marital_status: "married",
    ...lahoreAreas[0],
  },

  // ── GYNECOLOGIST ──
  {
    full_name: "Nusrat Parveen",
    email: "dr.nusrat.parveen@apnadoctor.pk",
    phone: "0300-1234061",
    gender: "female",
    specialization: "Gynecologist",
    qualification: "MBBS, FCPS (Obstetrics & Gynecology)",
    experience: 19,
    bio: "Dr. Nusrat Parveen is a senior obstetrician and gynecologist with 19 years of experience. She specializes in high-risk pregnancy, laparoscopic gynecological surgery, and management of infertility. She has delivered over 5,000 babies and is known for her compassionate care.",
    clinic_name: "Nusrat Women's Hospital",
    clinic_address: "28 Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-GYN-70061",
    consultation_fee: 2500,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.9,
    total_reviews: 634,
    total_appointments: 2300,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Shazia Nawaz",
    email: "dr.shazia.nawaz@apnadoctor.pk",
    phone: "0300-1234062",
    gender: "female",
    specialization: "Gynecologist",
    qualification: "MBBS, FCPS (Gynecology), Fellowship Laparoscopy",
    experience: 13,
    bio: "Dr. Shazia Nawaz is a gynecologist with advanced laparoscopic skills. She performs minimally invasive surgery for endometriosis, uterine fibroids, ovarian cysts, and ectopic pregnancy. She trained in laparoscopic surgery in Germany and follows the latest surgical protocols.",
    clinic_name: "DHA Womens Surgical Centre",
    clinic_address: "91 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-GYN-70062",
    consultation_fee: 3000,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 345,
    total_appointments: 980,
    marital_status: "married",
    ...lahoreAreas[1],
  },
  {
    full_name: "Fareena Tariq",
    email: "dr.fareena.tariq@apnadoctor.pk",
    phone: "0300-1234063",
    gender: "female",
    specialization: "Gynecologist",
    qualification: "MBBS, MRCOG (UK), FCPS",
    experience: 15,
    bio: "Dr. Fareena Tariq holds the MRCOG from the Royal College of Obstetricians and Gynaecologists UK. She specializes in recurrent miscarriage, polycystic ovary syndrome (PCOS), and reproductive medicine. She runs an infertility clinic and has helped hundreds of couples achieve pregnancy.",
    clinic_name: "Cantt Fertility & Womens Clinic",
    clinic_address: "18 Sarwar Road, Cantt, Lahore",
    pmdc_number: "PMDC-GYN-70063",
    consultation_fee: 3500,
    languages: ["Urdu", "English"],
    average_rating: 4.9,
    total_reviews: 412,
    total_appointments: 1200,
    marital_status: "married",
    ...lahoreAreas[6],
  },
  {
    full_name: "Huma Arif",
    email: "dr.huma.arif@apnadoctor.pk",
    phone: "0300-1234064",
    gender: "female",
    specialization: "Gynecologist",
    qualification: "MBBS, FCPS (Obstetrics & Gynecology)",
    experience: 10,
    bio: "Dr. Huma Arif is an obstetrician and gynecologist specializing in antenatal care, normal and cesarean delivery, and postpartum care. She is passionate about maternal mental health and provides holistic support throughout pregnancy. She works at Bahria Town Hospital.",
    clinic_name: "Bahria Womens Care Centre",
    clinic_address: "Sector C Main Road, Bahria Town, Lahore",
    pmdc_number: "PMDC-GYN-70064",
    consultation_fee: 2000,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.7,
    total_reviews: 289,
    total_appointments: 840,
    marital_status: "married",
    ...lahoreAreas[4],
  },
  {
    full_name: "Raheela Siddiq",
    email: "dr.raheela.siddiq@apnadoctor.pk",
    phone: "0300-1234065",
    gender: "female",
    specialization: "Gynecologist",
    qualification: "MBBS, MCPS (Gynecology)",
    experience: 8,
    bio: "Dr. Raheela Siddiq is a gynecologist with special interest in adolescent gynecology and menstrual disorders. She provides a safe and supportive environment for young women to discuss reproductive health issues. She also has expertise in contraceptive counseling.",
    clinic_name: "Johar Town Womens Health Centre",
    clinic_address: "55 Khayaban-e-Jinnah, Johar Town, Lahore",
    pmdc_number: "PMDC-GYN-70065",
    consultation_fee: 1800,
    languages: ["Urdu", "English"],
    average_rating: 4.6,
    total_reviews: 198,
    total_appointments: 560,
    marital_status: "single",
    ...lahoreAreas[3],
  },

  // ── NEUROLOGIST ──
  {
    full_name: "Zafar Iqbal Mirza",
    email: "dr.zafar.mirza@apnadoctor.pk",
    phone: "0300-1234071",
    gender: "male",
    specialization: "Neurologist",
    qualification: "MBBS, FCPS (Neurology), Fellowship Epilepsy (UK)",
    experience: 20,
    bio: "Professor Zafar Iqbal Mirza is a senior neurologist and epileptologist with 20 years of experience. He is an expert in epilepsy surgery evaluation, EEG interpretation, and management of status epilepticus. He has trained at National Hospital for Neurology and Neurosurgery, London.",
    clinic_name: "Lahore Neurology Centre",
    clinic_address: "50 Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-NEURO-80071",
    consultation_fee: 4000,
    languages: ["Urdu", "English"],
    average_rating: 4.9,
    total_reviews: 478,
    total_appointments: 1380,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Aneela Arooj",
    email: "dr.aneela.arooj@apnadoctor.pk",
    phone: "0300-1234072",
    gender: "female",
    specialization: "Neurologist",
    qualification: "MBBS, FCPS (Neurology)",
    experience: 11,
    bio: "Dr. Aneela Arooj is a neurologist specializing in headache disorders, migraine, and sleep neurology. She uses a multidisciplinary approach for chronic migraine and has established a headache clinic offering botulinum toxin injections and nerve blocks.",
    clinic_name: "DHA Headache & Neurology Clinic",
    clinic_address: "102 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-NEURO-80072",
    consultation_fee: 3000,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 267,
    total_appointments: 720,
    marital_status: "married",
    ...lahoreAreas[1],
  },
  {
    full_name: "Tariq Jameel Aziz",
    email: "dr.tariq.aziz@apnadoctor.pk",
    phone: "0300-1234073",
    gender: "male",
    specialization: "Neurologist",
    qualification: "MBBS, FCPS (Neurology), Fellowship Stroke (Canada)",
    experience: 17,
    bio: "Dr. Tariq Jameel Aziz is a stroke neurologist trained in Canada. He specializes in acute stroke management, thrombolysis, and stroke prevention. He established the first stroke unit at a Lahore hospital and advocates for the 'Time is Brain' approach to stroke care.",
    clinic_name: "Cantt Stroke & Neurology Centre",
    clinic_address: "25 Sarwar Road, Cantt, Lahore",
    pmdc_number: "PMDC-NEURO-80073",
    consultation_fee: 3500,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 334,
    total_appointments: 920,
    marital_status: "married",
    ...lahoreAreas[6],
  },
  {
    full_name: "Maryam Sajid",
    email: "dr.maryam.sajid@apnadoctor.pk",
    phone: "0300-1234074",
    gender: "female",
    specialization: "Neurologist",
    qualification: "MBBS, MCPS (Neurology)",
    experience: 8,
    bio: "Dr. Maryam Sajid is a neurologist with special interest in multiple sclerosis and neuroimmunology. She manages patients with MS using disease-modifying therapies and provides comprehensive MS care. She also has expertise in neuromyelitis optica spectrum disorder.",
    clinic_name: "Model Town Neurology Clinic",
    clinic_address: "11 Main Boulevard, Model Town, Lahore",
    pmdc_number: "PMDC-NEURO-80074",
    consultation_fee: 2500,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.6,
    total_reviews: 178,
    total_appointments: 480,
    marital_status: "single",
    ...lahoreAreas[2],
  },
  {
    full_name: "Waseem Abbas",
    email: "dr.waseem.abbas@apnadoctor.pk",
    phone: "0300-1234075",
    gender: "male",
    specialization: "Neurologist",
    qualification:
      "MBBS, FCPS (Neurology), Fellowship Movement Disorders (USA)",
    experience: 15,
    bio: "Dr. Waseem Abbas is a movement disorder specialist trained in the USA. He is an expert in Parkinson's disease, tremor, dystonia, and deep brain stimulation candidacy assessment. He has published research on Parkinson's disease in the Pakistani population.",
    clinic_name: "Bahria Neurology Clinic",
    clinic_address: "Sector C Main Road, Bahria Town, Lahore",
    pmdc_number: "PMDC-NEURO-80075",
    consultation_fee: 3000,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 289,
    total_appointments: 790,
    marital_status: "married",
    ...lahoreAreas[4],
  },

  // ── ORTHOPEDIC ──
  {
    full_name: "Imtiaz Ahmed Chaudhry",
    email: "dr.imtiaz.chaudhry@apnadoctor.pk",
    phone: "0300-1234081",
    gender: "male",
    specialization: "Orthopedic",
    qualification:
      "MBBS, FCPS (Orthopedic Surgery), Fellowship Joint Replacement (UK)",
    experience: 21,
    bio: "Professor Imtiaz Ahmed Chaudhry is a senior orthopedic surgeon with 21 years of experience in joint replacement surgery. He has performed over 3,000 total knee and hip replacements. He trained in joint replacement surgery at Oxford and is among Pakistan's leading arthroplasty surgeons.",
    clinic_name: "Lahore Joint Replacement Centre",
    clinic_address: "60 Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-ORTH-90081",
    consultation_fee: 4000,
    languages: ["Urdu", "English"],
    average_rating: 4.9,
    total_reviews: 523,
    total_appointments: 1650,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Rabia Jehangir",
    email: "dr.rabia.jehangir@apnadoctor.pk",
    phone: "0300-1234082",
    gender: "female",
    specialization: "Orthopedic",
    qualification: "MBBS, FCPS (Orthopedic Surgery)",
    experience: 9,
    bio: "Dr. Rabia Jehangir is one of Lahore's few female orthopedic surgeons. She specializes in pediatric orthopedics, fracture management, and clubfoot treatment. She has a special interest in scoliosis and spinal deformities in children and adolescents.",
    clinic_name: "DHA Orthopedics Clinic",
    clinic_address: "112 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-ORTH-90082",
    consultation_fee: 2500,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 234,
    total_appointments: 630,
    marital_status: "married",
    ...lahoreAreas[1],
  },
  {
    full_name: "Shehryar Khan",
    email: "dr.shehryar.khan@apnadoctor.pk",
    phone: "0300-1234083",
    gender: "male",
    specialization: "Orthopedic",
    qualification:
      "MBBS, FCPS (Orthopedic Surgery), Fellowship Sports Medicine (Germany)",
    experience: 14,
    bio: "Dr. Shehryar Khan is a sports medicine and orthopedic surgeon specializing in arthroscopic surgery of knee, shoulder, and hip. He manages sports injuries including ACL tears, rotator cuff tears, and cartilage damage. He is the team physician for several Lahore sports teams.",
    clinic_name: "Cantt Sports Orthopedic Centre",
    clinic_address: "35 Sarwar Road, Cantt, Lahore",
    pmdc_number: "PMDC-ORTH-90083",
    consultation_fee: 3000,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.8,
    total_reviews: 312,
    total_appointments: 870,
    marital_status: "married",
    ...lahoreAreas[6],
  },
  {
    full_name: "Adnan Riaz",
    email: "dr.adnan.riaz@apnadoctor.pk",
    phone: "0300-1234084",
    gender: "male",
    specialization: "Orthopedic",
    qualification: "MBBS, FCPS (Orthopedic Surgery), Diploma Spine Surgery",
    experience: 12,
    bio: "Dr. Adnan Riaz is a spine surgeon specializing in minimally invasive spine surgery, disc herniation, spinal stenosis, and scoliosis correction. He uses intraoperative navigation systems for precision in complex spine surgery. He trained at Aga Khan University Hospital.",
    clinic_name: "Johar Town Spine & Ortho Centre",
    clinic_address: "66 Khayaban-e-Jinnah, Johar Town, Lahore",
    pmdc_number: "PMDC-ORTH-90084",
    consultation_fee: 3500,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 267,
    total_appointments: 720,
    marital_status: "single",
    ...lahoreAreas[3],
  },
  {
    full_name: "Shahzad Aslam",
    email: "dr.shahzad.aslam@apnadoctor.pk",
    phone: "0300-1234085",
    gender: "male",
    specialization: "Orthopedic",
    qualification: "MBBS, MCPS (Orthopedic Surgery)",
    experience: 7,
    bio: "Dr. Shahzad Aslam is an orthopedic surgeon with focus on trauma surgery and fracture management. He manages complex fractures, polytrauma patients, and performs external and internal fixation procedures. He works in emergency orthopedics at Model Town Hospital.",
    clinic_name: "Model Town Trauma & Ortho Clinic",
    clinic_address: "3 Main Boulevard, Model Town, Lahore",
    pmdc_number: "PMDC-ORTH-90085",
    consultation_fee: 2000,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.5,
    total_reviews: 189,
    total_appointments: 520,
    marital_status: "married",
    ...lahoreAreas[2],
  },

  // ── PEDIATRICIAN ──
  {
    full_name: "Shamim Akhtar",
    email: "dr.shamim.akhtar@apnadoctor.pk",
    phone: "0300-1234091",
    gender: "female",
    specialization: "Pediatrician",
    qualification: "MBBS, FCPS (Pediatrics), Fellowship Neonatology",
    experience: 22,
    bio: "Professor Shamim Akhtar is a senior pediatrician and neonatologist with 22 years of experience. She specializes in care of premature and critically ill newborns, neonatal jaundice, and respiratory distress in newborns. She has trained hundreds of pediatric residents.",
    clinic_name: "Lahore Children & Newborn Centre",
    clinic_address: "70 Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-PED-100091",
    consultation_fee: 2000,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.9,
    total_reviews: 678,
    total_appointments: 2500,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Raza Haider",
    email: "dr.raza.haider@apnadoctor.pk",
    phone: "0300-1234092",
    gender: "male",
    specialization: "Pediatrician",
    qualification: "MBBS, FCPS (Pediatrics)",
    experience: 12,
    bio: "Dr. Raza Haider is a consultant pediatrician specializing in childhood asthma, allergies, and respiratory diseases. He uses age-appropriate communication to involve children in their own healthcare and is known for his gentle approach with young patients.",
    clinic_name: "DHA Kids Health Centre",
    clinic_address: "120 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-PED-100092",
    consultation_fee: 1500,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 456,
    total_appointments: 1670,
    marital_status: "married",
    ...lahoreAreas[1],
  },
  {
    full_name: "Faria Khalil",
    email: "dr.faria.khalil@apnadoctor.pk",
    phone: "0300-1234093",
    gender: "female",
    specialization: "Pediatrician",
    qualification: "MBBS, FCPS (Pediatrics), Fellowship Pediatric Neurology",
    experience: 10,
    bio: "Dr. Faria Khalil is a pediatrician with sub-specialty training in pediatric neurology. She manages childhood epilepsy, cerebral palsy, developmental delays, and autism spectrum disorder. She works in a multidisciplinary team to provide comprehensive developmental pediatric care.",
    clinic_name: "Bahria Pediatric Neurology Clinic",
    clinic_address: "Sector C Main Road, Bahria Town, Lahore",
    pmdc_number: "PMDC-PED-100093",
    consultation_fee: 2000,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 312,
    total_appointments: 940,
    marital_status: "single",
    ...lahoreAreas[4],
  },
  {
    full_name: "Asad Mehmood",
    email: "dr.asad.mehmood@apnadoctor.pk",
    phone: "0300-1234094",
    gender: "male",
    specialization: "Pediatrician",
    qualification: "MBBS, MCPS (Pediatrics)",
    experience: 8,
    bio: "Dr. Asad Mehmood is a community pediatrician with focus on childhood nutrition, growth monitoring, and immunization programs. He counsels parents on breastfeeding, complementary feeding, and healthy development milestones. He runs a community child health program.",
    clinic_name: "Shadman Children Clinic",
    clinic_address: "17 Shadman Market Road, Shadman, Lahore",
    pmdc_number: "PMDC-PED-100094",
    consultation_fee: 1000,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.8,
    total_reviews: 389,
    total_appointments: 1420,
    marital_status: "married",
    ...lahoreAreas[7],
  },
  {
    full_name: "Yasmin Arshad",
    email: "dr.yasmin.arshad@apnadoctor.pk",
    phone: "0300-1234095",
    gender: "female",
    specialization: "Pediatrician",
    qualification: "MBBS, FCPS (Pediatrics), MRCPCH (UK)",
    experience: 16,
    bio: "Dr. Yasmin Arshad holds the MRCPCH from the Royal College of Paediatrics and Child Health UK. She specializes in pediatric gastroenterology, inflammatory bowel disease in children, and liver diseases. She is a visiting consultant at The Children's Hospital Lahore.",
    clinic_name: "Cantt Pediatric Gastro Centre",
    clinic_address: "42 Sarwar Road, Cantt, Lahore",
    pmdc_number: "PMDC-PED-100095",
    consultation_fee: 2500,
    languages: ["Urdu", "English"],
    average_rating: 4.9,
    total_reviews: 412,
    total_appointments: 1230,
    marital_status: "married",
    ...lahoreAreas[6],
  },

  // ── PSYCHIATRIST ──
  {
    full_name: "Yusuf Salahuddin",
    email: "dr.yusuf.salahuddin@apnadoctor.pk",
    phone: "0300-1234101",
    gender: "male",
    specialization: "Psychiatrist",
    qualification: "MBBS, FCPS (Psychiatry), MRCPsych (UK)",
    experience: 18,
    bio: "Dr. Yusuf Salahuddin is a consultant psychiatrist holding both FCPS and MRCPsych from the Royal College of Psychiatrists UK. He specializes in mood disorders, schizophrenia, and addiction psychiatry. He provides evidence-based pharmacotherapy and cognitive behavioral therapy.",
    clinic_name: "Lahore Mind & Wellness Centre",
    clinic_address: "80 Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-PSY-110101",
    consultation_fee: 3500,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 312,
    total_appointments: 870,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Samira Baig",
    email: "dr.samira.baig@apnadoctor.pk",
    phone: "0300-1234102",
    gender: "female",
    specialization: "Psychiatrist",
    qualification: "MBBS, FCPS (Psychiatry)",
    experience: 11,
    bio: "Dr. Samira Baig is a psychiatrist specializing in perinatal mental health, postpartum depression, and anxiety disorders in women. She provides psychotherapy and medication management in a supportive, non-judgmental environment. She also offers online consultations.",
    clinic_name: "DHA Psychiatric Care Centre",
    clinic_address: "135 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-PSY-110102",
    consultation_fee: 3000,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 234,
    total_appointments: 640,
    marital_status: "single",
    ...lahoreAreas[1],
  },
  {
    full_name: "Faheem Qasim",
    email: "dr.faheem.qasim@apnadoctor.pk",
    phone: "0300-1234103",
    gender: "male",
    specialization: "Psychiatrist",
    qualification: "MBBS, FCPS (Psychiatry), Diploma CBT",
    experience: 9,
    bio: "Dr. Faheem Qasim is a psychiatrist with expertise in cognitive behavioral therapy, addiction medicine, and adolescent psychiatry. He combines pharmacotherapy with structured psychotherapy for comprehensive mental health management. He is trained in motivational interviewing.",
    clinic_name: "Model Town Mental Health Clinic",
    clinic_address: "15 Main Boulevard, Model Town, Lahore",
    pmdc_number: "PMDC-PSY-110103",
    consultation_fee: 2500,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.6,
    total_reviews: 189,
    total_appointments: 510,
    marital_status: "married",
    ...lahoreAreas[2],
  },
  {
    full_name: "Kiran Zahid",
    email: "dr.kiran.zahid@apnadoctor.pk",
    phone: "0300-1234104",
    gender: "female",
    specialization: "Psychiatrist",
    qualification: "MBBS, MCPS (Psychiatry)",
    experience: 7,
    bio: "Dr. Kiran Zahid is a psychiatrist focusing on child and adolescent mental health including ADHD, autism spectrum disorder, and school-related anxiety. She uses play therapy techniques alongside medication and works closely with families and school counselors.",
    clinic_name: "Johar Town Child Mental Health Centre",
    clinic_address: "77 Khayaban-e-Jinnah, Johar Town, Lahore",
    pmdc_number: "PMDC-PSY-110104",
    consultation_fee: 2000,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 167,
    total_appointments: 450,
    marital_status: "single",
    ...lahoreAreas[3],
  },
  {
    full_name: "Bilal Sarwar",
    email: "dr.bilal.sarwar@apnadoctor.pk",
    phone: "0300-1234105",
    gender: "male",
    specialization: "Psychiatrist",
    qualification: "MBBS, FCPS (Psychiatry), Fellowship Geriatric Psychiatry",
    experience: 14,
    bio: "Dr. Bilal Sarwar is a psychiatrist with sub-specialty training in geriatric psychiatry. He specializes in dementia, Alzheimer's disease, late-life depression, and delirium management. He provides home visits for elderly patients who cannot travel to the clinic.",
    clinic_name: "Bahria Geriatric Mental Health Centre",
    clinic_address: "Sector C Main Road, Bahria Town, Lahore",
    pmdc_number: "PMDC-PSY-110105",
    consultation_fee: 3000,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 256,
    total_appointments: 700,
    marital_status: "married",
    ...lahoreAreas[4],
  },

  // ── UROLOGIST ──
  {
    full_name: "Rashid Usman",
    email: "dr.rashid.usman@apnadoctor.pk",
    phone: "0300-1234111",
    gender: "male",
    specialization: "Urologist",
    qualification: "MBBS, FCPS (Urology), Fellowship Endourology (USA)",
    experience: 17,
    bio: "Dr. Rashid Usman is a urologist and endourologist specializing in minimally invasive treatment of kidney stones using laser lithotripsy and PCNL. He has trained in the USA and has expertise in ureteroscopy, ESWL, and complex stone surgery.",
    clinic_name: "Lahore Urology & Stone Centre",
    clinic_address: "90 Main Boulevard, Gulberg III, Lahore",
    pmdc_number: "PMDC-URO-120111",
    consultation_fee: 3000,
    languages: ["Urdu", "English"],
    average_rating: 4.8,
    total_reviews: 345,
    total_appointments: 960,
    marital_status: "married",
    ...lahoreAreas[0],
  },
  {
    full_name: "Misbah Nasreen",
    email: "dr.misbah.nasreen@apnadoctor.pk",
    phone: "0300-1234112",
    gender: "female",
    specialization: "Urologist",
    qualification: "MBBS, FCPS (Urology)",
    experience: 9,
    bio: "Dr. Misbah Nasreen is one of Lahore's few female urologists. She specializes in female urology, urinary incontinence, pelvic floor disorders, and recurrent urinary tract infections. She provides a comfortable environment for women to discuss sensitive urological issues.",
    clinic_name: "DHA Female Urology Clinic",
    clinic_address: "145 Badar Commercial, DHA Phase 5, Lahore",
    pmdc_number: "PMDC-URO-120112",
    consultation_fee: 2500,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 212,
    total_appointments: 580,
    marital_status: "married",
    ...lahoreAreas[1],
  },
  {
    full_name: "Farhan Ijaz",
    email: "dr.farhan.ijaz@apnadoctor.pk",
    phone: "0300-1234113",
    gender: "male",
    specialization: "Urologist",
    qualification:
      "MBBS, FCPS (Urology), Fellowship Laparoscopic Urology (Germany)",
    experience: 14,
    bio: "Dr. Farhan Ijaz is a laparoscopic urologist with expertise in robotic-assisted and laparoscopic urological surgery. He performs laparoscopic nephrectomy, pyeloplasty, and radical prostatectomy. He trained in Germany and brings European surgical standards to Lahore.",
    clinic_name: "Cantt Surgical Urology Centre",
    clinic_address: "50 Sarwar Road, Cantt, Lahore",
    pmdc_number: "PMDC-URO-120113",
    consultation_fee: 3500,
    languages: ["Urdu", "English"],
    average_rating: 4.9,
    total_reviews: 289,
    total_appointments: 790,
    marital_status: "married",
    ...lahoreAreas[6],
  },
  {
    full_name: "Saeed Ahmad Gill",
    email: "dr.saeed.gill@apnadoctor.pk",
    phone: "0300-1234114",
    gender: "male",
    specialization: "Urologist",
    qualification: "MBBS, FCPS (Urology)",
    experience: 11,
    bio: "Dr. Saeed Ahmad Gill is a urologist specializing in benign prostatic hyperplasia (BPH), prostate cancer, and male infertility. He offers TURP and laser treatment for prostate enlargement and provides male fertility evaluation and treatment.",
    clinic_name: "Model Town Prostate & Urology Clinic",
    clinic_address: "20 Main Boulevard, Model Town, Lahore",
    pmdc_number: "PMDC-URO-120114",
    consultation_fee: 2500,
    languages: ["Urdu", "English", "Punjabi"],
    average_rating: 4.6,
    total_reviews: 234,
    total_appointments: 640,
    marital_status: "married",
    ...lahoreAreas[2],
  },
  {
    full_name: "Omar Shahid",
    email: "dr.omar.shahid@apnadoctor.pk",
    phone: "0300-1234115",
    gender: "male",
    specialization: "Urologist",
    qualification: "MBBS, MCPS (Urology)",
    experience: 7,
    bio: "Dr. Omar Shahid is a urologist with special interest in pediatric urology and congenital urological conditions. He manages hypospadias, undescended testes, vesicoureteral reflux, and posterior urethral valves in children. He trained at The Children's Hospital Lahore.",
    clinic_name: "Johar Town Pediatric Urology Clinic",
    clinic_address: "88 Khayaban-e-Jinnah, Johar Town, Lahore",
    pmdc_number: "PMDC-URO-120115",
    consultation_fee: 2000,
    languages: ["Urdu", "English"],
    average_rating: 4.7,
    total_reviews: 178,
    total_appointments: 490,
    marital_status: "single",
    ...lahoreAreas[3],
  },
];

async function seed() {
  console.log(`Seeding ${doctors.length} doctors...`);

  let successCount = 0;
  let errorCount = 0;

  for (const doctor of doctors) {
    // Create auth user
    const { data: authData, error: authError } =
      await supabase.auth.admin.createUser({
        email: doctor.email,
        password: "ApnaDoctor@2024",
        email_confirm: true,
      });

    if (authError) {
      console.error(`Auth error for ${doctor.email}:`, authError.message);
      errorCount++;
      continue;
    }

    const userId = authData.user.id;

    // Insert doctor record
    const { error: dbError } = await supabase.from("doctors").insert({
      id: userId,
      full_name: doctor.full_name,
      email: doctor.email,
      phone: doctor.phone,
      gender: doctor.gender,
      specialization: doctor.specialization,
      qualification: doctor.qualification,
      experience: doctor.experience,
      bio: doctor.bio,
      clinic_name: doctor.clinic_name,
      clinic_address: doctor.clinic_address,
      city: doctor.city,
      area: doctor.area,
      street: doctor.street,
      country: "PK",
      consultation_fee: doctor.consultation_fee,
      languages: doctor.languages,
      pmdc_number: doctor.pmdc_number,
      marital_status: doctor.marital_status,
      is_verified: true,
      is_active: true,
      average_rating: doctor.average_rating,
      total_reviews: doctor.total_reviews,
      total_appointments: doctor.total_appointments,
      verified_at: new Date().toISOString(),
    });

    if (dbError) {
      console.error(`DB error for ${doctor.email}:`, dbError.message);
      await supabase.auth.admin.deleteUser(userId);
      errorCount++;
      continue;
    }

    console.log(`✓ ${doctor.full_name} (${doctor.specialization})`);
    successCount++;
  }

  console.log(`\nDone! ${successCount} doctors seeded, ${errorCount} errors.`);
}

seed();
